before-script:
  - echo "Before script"

stages:
  - build
  - test
  - deploy
 
build:
  stage: build
  script:
    - echo "Building"
  
test:
  stage: test
  script:
    - echo "Testing"
    
deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying"