# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 09:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20170613_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='urlName',
            field=models.CharField(default='', editable=False, max_length=60, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', "Only alphanumeric characters and '-' are allowed.")]),
        ),
    ]
