# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0012_auto_20170616_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_interaction',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 20, 18, 21, 531795)),
        ),
    ]
