# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0013_question_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='last_interaction',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
