# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0014_auto_20170616_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='last_interaction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
