# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catieprofile',
            options={'verbose_name': 'CATie Profile', 'verbose_name_plural': 'CATie Profiles'},
        ),
    ]
