# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='content',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
