# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20170612_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('urlName', models.CharField(default='', max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', "Only alphanumeric characters and '-' are allowed.")])),
                ('video', models.URLField(default='')),
                ('slides', models.URLField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
