# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='urlSuffix',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
