# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='username',
            field=models.CharField(default='arc13', max_length=10),
            preserve_default=False,
        ),
    ]
