# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_calendarevent_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='username',
        ),
    ]
