# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170606_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ARiUser',
            new_name='ARiProfile',
        ),
    ]
