# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170607_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariprofile',
            name='secondYear',
            field=models.BooleanField(default=False),
        ),
    ]
