# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170613_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dateTime_1',
            field=models.DateTimeField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='dateTime_2',
            field=models.DateTimeField(default=False),
            preserve_default=False,
        ),
    ]
